# Generated by Django 5.0.3 on 2024-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(default='', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='telesettings',
            name='tg_token',
            field=models.CharField(max_length=200, verbose_name='Токен'),
        ),
    ]
